# Generated by Django 4.2.7 on 2023-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0002_alter_planttime_month_en_alter_planttime_month_lt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description in English language'),
        ),
        migrations.AlterField(
            model_name='color',
            name='description_lt',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description in Lithuanian language'),
        ),
        migrations.AlterField(
            model_name='selectedplant',
            name='blooming_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='enter blooming period'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description in English language'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description_lt',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description in English language'),
        ),
    ]
