# Generated by Django 4.2.7 on 2023-11-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0004_alter_plant_name_en_alter_plant_name_lt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedplant',
            name='zone_composition',
        ),
        migrations.AddField(
            model_name='selectedplant',
            name='zone',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='selected_plant', to='gardenplaner.zone', verbose_name='zone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gardenplaner.zone', verbose_name='zone'),
        ),
        migrations.DeleteModel(
            name='ZoneCoposition',
        ),
    ]
