# Generated by Django 4.2.7 on 2023-11-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0005_remove_selectedplant_zone_composition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='name_lt',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='name_en',
        ),
    ]
