# Generated by Django 4.2.7 on 2023-11-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0006_rename_name_lt_zone_name_remove_zone_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='composition',
            new_name='zone',
        ),
    ]
