# Generated by Django 4.2.7 on 2023-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0007_rename_composition_photo_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/images/', verbose_name='add image'),
        ),
    ]
