# Generated by Django 4.2.7 on 2023-11-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedplant',
            name='color',
        ),
    ]
