# Generated by Django 4.2.7 on 2023-11-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0010_remove_selectedplant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedplant',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selected_plant', to='gardenplaner.color', verbose_name='color'),
            preserve_default=False,
        ),
    ]
