# Generated by Django 4.2.7 on 2023-11-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenplaner', '0011_selectedplant_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='color',
            new_name='colors',
        ),
    ]
