# Generated by Django 4.2.7 on 2023-11-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenplaner', '0012_rename_color_plant_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_projects', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gardenplaner.zone', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='colors',
            field=models.ManyToManyField(related_name='plants', to='gardenplaner.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planting_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardenplaner.planttime', verbose_name='planting time'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardenplaner.type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='selectedplant',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_plants', to='gardenplaner.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='selectedplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_plants', to='gardenplaner.plant', verbose_name='plant'),
        ),
        migrations.AlterField(
            model_name='selectedplant',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_plants', to='gardenplaner.zone', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='garden_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='gardenplaner.gardenproject', verbose_name='garden project'),
        ),
    ]
